### PR TITLE
fix: missing dependency

### PR DESCRIPTION
**Pull request by Gozala**
In v11 I get following errors

```
playwright-test --help                                           ✭
node:internal/errors:484
    ErrorCaptureStackTrace(err);
    ^

Error [ERR_MODULE_NOT_FOUND]: Cannot find package 'execa' imported from /Users/gozala/Projects/entail/node_modules/.pnpm/playwright-test@11.0.0/node_modules/playwright-test/src/node/runner.js
    at new NodeError (node:internal/errors:393:5)
    at packageResolve (node:internal/modules/esm/resolve:860:9)
    at moduleResolve (node:internal/modules/esm/resolve:909:20)
    at defaultResolve (node:internal/modules/esm/resolve:1124:11)
    at nextResolve (node:internal/modules/esm/loader:163:28)
    at ESMLoader.resolve (node:internal/modules/esm/loader:841:30)
    at ESMLoader.getModuleJob (node:internal/modules/esm/loader:424:18)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/module_job:76:40)
    at link (node:internal/modules/esm/module_job:75:36) {
  code: 'ERR_MODULE_NOT_FOUND'
}

Node.js v18.12.1
```

Which I believe due to fact that `execa` is listed in dev dependencies, yet it is sued as actual dependency

### CODE REVIEW

**Review by hugomrdias — APPROVED** [review]

**Comment by hugomrdias** [comment]
can you update the lock file please

**Comment by hugomrdias** [comment]
Should be fixed in main.
Feel free to re open if this still happens.

Thank you 🙏🏼

**Comment by Gozala** [comment]
Hey @hugomrdias it still not fixed because change that landed did not moved execa to deps see
https://github.com/hugomrdias/playwright-test/commit/51b44876718ffc874702ed5b3bd8904ab757608f

So I still see same error

```
node:internal/process/esm_loader:97
    internalBinding('errors').triggerUncaughtException(
                              ^

Error [ERR_MODULE_NOT_FOUND]: Cannot find package 'execa' imported from /Users/gozala/Projects/entail/node_modules/.pnpm/playwright-test@11.0.1/node_modules/playwright-test/src/node/runner.js
Did you mean to import execa@1.0.0/node_modules/execa/index.js?
    at new NodeError (node:internal/errors:393:5)
    at packageResolve (node:internal/modules/esm/resolve:860:9)
    at moduleResolve (node:internal/modules/esm/resolve:909:20)
    at defaultResolve (node:internal/modules/esm/resolve:1124:11)
    at nextResolve (node:internal/modules/esm/loader:163:28)
    at ESMLoader.resolve (node:internal/modules/esm/loader:841:30)
    at ESMLoader.getModuleJob (node:internal/modules/esm/loader:424:18)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/module_job:76:40)
    at link (node:internal/modules/esm/module_job:75:36)
```

**Comment by hugomrdias** [comment]
should be good now

**Pull request closed without merging**
